<!DOCTYPE html>
<html lang="en">
<head>
<title>Privacy Policy</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

 <link rel="stylesheet" type="text/css" href="assets/css/privacyPolicyPage.css">

 <link rel="shortcut icon" sizes="16x16 32x32 64x64" href="assets/css/images/logo5.png"/>

</head>
<body>

<div class="container privacy">
	<div class="card">
		<div class="col-sm-12">
			<h4 class="text-center"><strong>Privacy Policy</strong></h4>
			<div class="card-body">
			
				<div class="row justify-align-center">
					<p class="text-center"><strong>ROOTS</strong> ("us", "we", or "our")  operates the <span class="text-success">www.roots.ph</span> website (hereinafter referred to as the "Service").</p>
				
					<p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from <span class="text-success">www.roots.ph</span></p>

					<div class="card-body">
						<p class="col"><strong>Definitions</strong>
							<ul>
								<li><u>Service</u>
									<p class="col-sm-10">Service is the <span class="text-success">www.roots.ph</span> website operated by <strong>ROOTS</strong>
									</p>
								</li>
								<li><u>Personal Data</u>
									<p class="col-sm-10">Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
									</p>
								</li>
								<li><u>Usage Data</u>
									<p class="col-sm-10">Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
									</p>
								</li>
								<li><u>Cookies</u>
									<p class="col-sm-10">Cookies are small files stored on your device (computer or mobile device).
									</p>
								</li>
							</ul>
						</p>
					</div>
					<div class="card-body">
						<p class="col"><strong>Information Collection and Use</strong> <br>
							  We collect several different types of information for various purposes to provide and improve our Service to you.
						</p>
					</div>
					<div class="card-body">
						<p><strong>Types of Data Collected </strong> 							
							<ul>
							  	<li><u>Personal Data </u>
							  		<p class="col-sm-12">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you("Personal Data"). Personally identifiable information may include, but is not limited to:
							  			<ol>
							  				<li>Email address</li>
							  				<li>First name and last name</li>
							  				<li>Phone number</li>
							  				<li>Address, State, Province, ZIP/Postal code, City</li>
							  				<li>Cookies and Usage Data</li>
							  			</ol>
							  			
							  		</p>
							  	</li>
							  	<li><u>Usage Data </u>
							  		<p class="col-sm-12">We may also collect information how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
							  	</li>
							  	<li><u>Cookies Data </u>
							  		<p class="col-sm-12">We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
							  		<p class="col-sm-12">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Service.</p>
							  		<p class="col-sm-12">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
							  		<p class="col-sm-12">Examples of Cookies we use:
							  			<ul>
							  				<li>Session Cookies. We use Session Cookies to operate our Service.</li>
							  				<li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
							  				<li>Security Cookies. We use Security Cookies for security purposes.</li>
							  			</ul>
							  		</p>
							  	</li>
							</ul>							  
						</p>
					</div>
					<div class="card-body">
						<p><strong>Use of Data </strong> <br>
							ROOTS uses the collected data for various purposes:
							<ul>
								<li>To provide and maintain the Service</li>
								<li>To notify you about changes to our Service</li>
								<li>To allow you to participate in interactive features of our Service when you choose to do so</li>
								<li>To provide customer care and support</li>
								<li>To provide analysis or valuable information so that we can improve the Service</li>
								<li>To monitor the usage of the Service</li>
								<li>To detect, prevent and address technical issues</li>
							</ul>
						</p>
					</div>
					<div class="card-body">
						<p><strong>Transfer Of Data  </strong></p>
						<p class="col-sm-12">Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ thanthose from your jurisdiction.</p>
						<p class="col-sm-12">If you are located outside Philippines and choose to provide information to us, please note that we transfer the data, including Personal Data, to Philippines and process it there.</p>
						<p class="col-sm-12">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
						<p class="col-sm-12">ROOTS will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
					</div>
					<div class="card-body">
						<p><strong>Disclosure Of Data   </strong> <br>
						</p>
					</div>
					<div class="card-body">
						<p><strong>Legal Requirements</strong> <br>
							<p>ROOTS may disclose your Personal Data in the good faith belief that such action is necessary to:
								<ul>
									<li>To comply with a legal obligation</li>
									<li>To protect and defend the rights or property of <strong>ROOTS</strong></li>
									<li>To prevent or investigate possible wrongdoing in connection with the Service</li>
									<li>To protect the personal safety of users of the Service or the public</li>
									<li>To protect against legal liability</li>
								</ul>
							</p>
						</p>
					</div>
					<div class="card-body">
						<p><strong>Security of Data</strong> <br>
							<p class="col-sm-12">The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
						</p>					
					</div>
					<div class="card-body">
						<p><strong>Service Providers </strong> <br>
							<p class="col-sm-12">We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used. </p>
							<p class="col-sm-12">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
						</p>						
					</div>
					<div class="card-body">
						<p><strong>Links to Other Sites </strong> <br>
							<p class="col-sm-12">Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
							<p class="col-sm-12">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
						</p>
					</div>
					<div class="card-body">
						<p><strong>Children's Privacy </strong> <br>
							<p class="col-sm-12">Our Service does not address anyone under the age of 18 ("Children").</p>
							<p class="col-sm-12">We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
						</p>
					</div>
					<div class="card-body">
						<p><strong>Changes to This Privacy Policy </strong> <br>
							<p class="col-sm-12">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
							<p class="col-sm-12">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.</p>
							<p class="col-sm-12">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
						</p>
					</div>
					<div class="card-body">
						<p><strong>Contact Us </strong> <br>
							<p class="col-sm-12">If you have any questions about this Privacy Policy, please contact us:</p>
							<ul>
								<li>By email: roots.monlight@gmail.com</li>
								<li>By visiting this page on our website: www.roots.ph/contact</li>
								<li>By phone number: (046) 481-7938</li>
							</ul>
						</p>
						
					</div>		
			</div>
		</div>
	</div>
</div>
<button onclick="topFunction()" id="myBtn" title="Go to top"><span class="fa fa-angle-double-up"></span></button>

<script type="text/javascript">
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    document.getElementById("myBtn").style.display = "block";
  } else {
    document.getElementById("myBtn").style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0;
}

</script>
</body>
</html>